version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: journal-postgres
    environment:
      - POSTGRES_DB=journal_db
      - POSTGRES_USER=admin69
      - POSTGRES_PASSWORD=admin69
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin69 -d journal_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: journal-adminer
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
    name: journal_pgdata
