// <auto-generated />
using System;
using JournalApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JournalApi.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20251214144143_AddRefreshTokenTable")]
    partial class AddRefreshTokenTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JournalApi.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<bool>("IsLate")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("boolean");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "LessonId" }, "IX_Attendances_LessonId");

                    b.HasIndex(new[] { "StudentId" }, "IX_Attendances_StudentId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("JournalApi.Models.EducationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("EducationTypes_pkey");

                    b.ToTable("EducationTypes");
                });

            modelBuilder.Entity("JournalApi.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("Employees_pkey");

                    b.HasIndex(new[] { "Login" }, "Employees_Login_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "Employees_Phone_key")
                        .IsUnique();

                    b.HasIndex(new[] { "PostId" }, "IX_Employees_PostId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("JournalApi.Models.EmployeePost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Post")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("Posts_pkey");

                    b.ToTable("EmployeePosts");
                });

            modelBuilder.Entity("JournalApi.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Grade1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("Grade");

                    b.HasKey("Id")
                        .HasName("Grades_pkey");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("JournalApi.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Course")
                        .HasColumnType("integer");

                    b.Property<int>("CuratorId")
                        .HasColumnType("integer");

                    b.Property<int>("SpecialityId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("Groups_pkey");

                    b.HasIndex(new[] { "CuratorId" }, "IX_Groups_CuratorId");

                    b.HasIndex(new[] { "SpecialityId" }, "IX_Groups_SpecialityId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("JournalApi.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("LessonTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("Lessons_pkey");

                    b.HasIndex(new[] { "GroupId" }, "IX_Lessons_GroupId");

                    b.HasIndex(new[] { "LessonTypeId" }, "IX_Lessons_LessonTypeId");

                    b.HasIndex(new[] { "SubjectId" }, "IX_Lessons_SubjectId");

                    b.HasIndex(new[] { "TeacherId" }, "IX_Lessons_TeacherId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("JournalApi.Models.LessonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id")
                        .HasName("LessonTypes_pkey");

                    b.ToTable("LessonTypes");
                });

            modelBuilder.Entity("JournalApi.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("JournalApi.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("JournalApi.Models.Speciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id")
                        .HasName("Specialities_pkey");

                    b.ToTable("Specialities");
                });

            modelBuilder.Entity("JournalApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Login")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("Students_pkey");

                    b.HasIndex(new[] { "GroupId" }, "IX_Students_GroupId");

                    b.HasIndex(new[] { "Login" }, "Students_Login_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "Students_Phone_key")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("JournalApi.Models.StudentGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("GradeId")
                        .HasColumnType("integer");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("StudentGrades_pkey");

                    b.HasIndex(new[] { "GradeId" }, "IX_StudentGrades_GradeId");

                    b.HasIndex(new[] { "LessonId" }, "IX_StudentGrades_LessonId");

                    b.HasIndex(new[] { "StudentId" }, "IX_StudentGrades_StudentId");

                    b.ToTable("StudentGrades");
                });

            modelBuilder.Entity("JournalApi.Models.StudyDuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EducationTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("StudyDurations_pkey");

                    b.HasIndex(new[] { "EducationTypeId" }, "IX_StudyDurations_EducationTypeId");

                    b.ToTable("StudyDurations");
                });

            modelBuilder.Entity("JournalApi.Models.StudyDurationSpeciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SpecialityId")
                        .HasColumnType("integer");

                    b.Property<int>("StudyDurationId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("StudyDurationSpeciality_pkey");

                    b.HasIndex(new[] { "SpecialityId" }, "IX_StudyDurationSpeciality_SpecialityId");

                    b.HasIndex(new[] { "StudyDurationId" }, "IX_StudyDurationSpeciality_StudyDurationId");

                    b.ToTable("StudyDurationSpeciality", (string)null);
                });

            modelBuilder.Entity("JournalApi.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id")
                        .HasName("Subjects_pkey");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("JournalApi.Models.SubjectEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PossibleEmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("SubjectEmployee_pkey");

                    b.HasIndex(new[] { "PossibleEmployeeId" }, "IX_SubjectEmployee_PossibleEmployeeId");

                    b.HasIndex(new[] { "SubjectId" }, "IX_SubjectEmployee_SubjectId");

                    b.ToTable("SubjectEmployee", (string)null);
                });

            modelBuilder.Entity("JournalApi.Models.SubjectSpecialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SpecialityId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("SubjectSpecialty_pkey");

                    b.HasIndex(new[] { "SpecialityId" }, "IX_SubjectSpecialty_SpecialityId");

                    b.HasIndex(new[] { "SubjectId" }, "IX_SubjectSpecialty_SubjectId");

                    b.ToTable("SubjectSpecialty", (string)null);
                });

            modelBuilder.Entity("JournalApi.Models.Attendance", b =>
                {
                    b.HasOne("JournalApi.Models.Lesson", "Lesson")
                        .WithMany("Attendances")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JournalApi.Models.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JournalApi.Models.Employee", b =>
                {
                    b.HasOne("JournalApi.Models.EmployeePost", "Post")
                        .WithMany("Employees")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("Employees_PostId_fkey");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("JournalApi.Models.Group", b =>
                {
                    b.HasOne("JournalApi.Models.Employee", "Curator")
                        .WithMany("Groups")
                        .HasForeignKey("CuratorId")
                        .IsRequired()
                        .HasConstraintName("Groups_CuratorId_fkey");

                    b.HasOne("JournalApi.Models.Speciality", "Speciality")
                        .WithMany("Groups")
                        .HasForeignKey("SpecialityId")
                        .IsRequired()
                        .HasConstraintName("Groups_SpecialityId_fkey");

                    b.Navigation("Curator");

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("JournalApi.Models.Lesson", b =>
                {
                    b.HasOne("JournalApi.Models.Group", "Group")
                        .WithMany("Lessons")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("Lessons_GroupId_fkey");

                    b.HasOne("JournalApi.Models.LessonType", "LessonType")
                        .WithMany("Lessons")
                        .HasForeignKey("LessonTypeId")
                        .IsRequired()
                        .HasConstraintName("Lessons_LessonTypeId_fkey");

                    b.HasOne("JournalApi.Models.Subject", "Subject")
                        .WithMany("Lessons")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("Lessons_SubjectId_fkey");

                    b.HasOne("JournalApi.Models.Employee", "Teacher")
                        .WithMany("Lessons")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("Lessons_TeacherId_fkey");

                    b.Navigation("Group");

                    b.Navigation("LessonType");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("JournalApi.Models.Student", b =>
                {
                    b.HasOne("JournalApi.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("Students_GroupId_fkey");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("JournalApi.Models.StudentGrade", b =>
                {
                    b.HasOne("JournalApi.Models.Grade", "Grade")
                        .WithMany("StudentGrades")
                        .HasForeignKey("GradeId")
                        .IsRequired()
                        .HasConstraintName("StudentGrades_GradeId_fkey");

                    b.HasOne("JournalApi.Models.Lesson", "Lesson")
                        .WithMany("StudentGrades")
                        .HasForeignKey("LessonId")
                        .IsRequired()
                        .HasConstraintName("StudentGrades_LessonId_fkey");

                    b.HasOne("JournalApi.Models.Student", "Student")
                        .WithMany("StudentGrades")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("StudentGrades_StudentId_fkey");

                    b.Navigation("Grade");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JournalApi.Models.StudyDuration", b =>
                {
                    b.HasOne("JournalApi.Models.EducationType", "EducationType")
                        .WithMany("StudyDurations")
                        .HasForeignKey("EducationTypeId")
                        .IsRequired()
                        .HasConstraintName("StudyDurations_EducationTypeId_fkey");

                    b.Navigation("EducationType");
                });

            modelBuilder.Entity("JournalApi.Models.StudyDurationSpeciality", b =>
                {
                    b.HasOne("JournalApi.Models.Speciality", "Speciality")
                        .WithMany("StudyDurationSpecialities")
                        .HasForeignKey("SpecialityId")
                        .IsRequired()
                        .HasConstraintName("StudyDurationSpeciality_SpecialityId_fkey");

                    b.HasOne("JournalApi.Models.StudyDuration", "StudyDuration")
                        .WithMany("StudyDurationSpecialities")
                        .HasForeignKey("StudyDurationId")
                        .IsRequired()
                        .HasConstraintName("StudyDurationSpeciality_StudyDurationId_fkey");

                    b.Navigation("Speciality");

                    b.Navigation("StudyDuration");
                });

            modelBuilder.Entity("JournalApi.Models.SubjectEmployee", b =>
                {
                    b.HasOne("JournalApi.Models.Employee", "PossibleEmployee")
                        .WithMany("SubjectEmployees")
                        .HasForeignKey("PossibleEmployeeId")
                        .IsRequired()
                        .HasConstraintName("SubjectEmployee_PossibleEmployeeId_fkey");

                    b.HasOne("JournalApi.Models.Subject", "Subject")
                        .WithMany("SubjectEmployees")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("SubjectEmployee_SubjectId_fkey");

                    b.Navigation("PossibleEmployee");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("JournalApi.Models.SubjectSpecialty", b =>
                {
                    b.HasOne("JournalApi.Models.Speciality", "Speciality")
                        .WithMany("SubjectSpecialties")
                        .HasForeignKey("SpecialityId")
                        .IsRequired()
                        .HasConstraintName("SubjectSpecialty_SpecialityId_fkey");

                    b.HasOne("JournalApi.Models.Subject", "Subject")
                        .WithMany("SubjectSpecialties")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("SubjectSpecialty_SubjectId_fkey");

                    b.Navigation("Speciality");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("JournalApi.Models.EducationType", b =>
                {
                    b.Navigation("StudyDurations");
                });

            modelBuilder.Entity("JournalApi.Models.Employee", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Lessons");

                    b.Navigation("SubjectEmployees");
                });

            modelBuilder.Entity("JournalApi.Models.EmployeePost", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("JournalApi.Models.Grade", b =>
                {
                    b.Navigation("StudentGrades");
                });

            modelBuilder.Entity("JournalApi.Models.Group", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("JournalApi.Models.Lesson", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("StudentGrades");
                });

            modelBuilder.Entity("JournalApi.Models.LessonType", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("JournalApi.Models.Speciality", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("StudyDurationSpecialities");

                    b.Navigation("SubjectSpecialties");
                });

            modelBuilder.Entity("JournalApi.Models.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("StudentGrades");
                });

            modelBuilder.Entity("JournalApi.Models.StudyDuration", b =>
                {
                    b.Navigation("StudyDurationSpecialities");
                });

            modelBuilder.Entity("JournalApi.Models.Subject", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("SubjectEmployees");

                    b.Navigation("SubjectSpecialties");
                });
#pragma warning restore 612, 618
        }
    }
}
